### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by YCP991** [dis-GU-ise/C-Homework#1]
Some comments should be added in the code ( Manually funny ) .

**Comment by dis-GU-ise** [comment]
REJECT！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dis-GU-ise/C-Homework"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月10日(星期三) 下午2:10
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[dis-GU-ise/C-Homework] Comments (Issue #1)





 
Some comments should be added in the code ( Manually funny ) .
